# Values to change

DEBUG = True
HOST = "localhost"
PORT = 5000
PLAYER_AMOUNT = 2
EACH_CARD_IN_DECK = 3
WRONG_MESSAGE_TOLERANCE = 3
GAMES_AMOUNT = 1
START_MONEY = 2
START_CARDS_AMOUNT = 2

# Constants to not change (unless needed)
PARAM_SPLITTER = "^"
COMMAND_END = "~"
CONTROL_CHAR_REPLACE = "_"
